sudo: false

language: node_js
node_js:
  - "0.10.40"

cache:
  directories:
    - $HOME/.meteor
    - $HOME/.npm

before_install:
  # Only install meteor if it's not in the cache
  - "if [ ! -e ~/.meteor/meteor ]; then curl https://install.meteor.com | /bin/sh; fi"
  # This will let us use "meteor" in the script
  - export PATH="$HOME/.meteor:$PATH"
  # Install Chimp which actually runs the tests
  - npm install chimp

script: SELENIUM_BROWSER=phantomjs node tests/run.js
